modLoader="javafml"
loaderVersion="[41,)"
logoFile="logo.png"
license="MIT"

[[mods]]
    modId="minemenu"
    version="${file.jarVersion}"
    displayName="MineMenu"
    displayURL="https://minecraft.curseforge.com/projects/minemenu"
    issueTrackerURL="https://github.com/dmillerw/MineMenu/issues"
    authors="dmillerw, Girafi"
    credits="Koeddk"
    description='''
    MineMenu supports key bindings, commands, and creative functions to make your life easier.
    '''

[[dependencies.minemenu]]
    modId="forge"
    mandatory=true
    versionRange="[41.0.64,)"
    ordering="NONE"
    side="BOTH"